### ISSUE TITLE
BUIP-HF: test plan needs to be separated out from the tech spec

### ISSUE THREAD

**Issue by ftrader** [BitcoinUnlimited/BUIP#50]
I feel the right place for the test plan is not in the tech spec itself, but rather somewhere in the doc/ folder of the source tree.

But the primary concern is to separate it out first of all.

Reasons
- test plan is long in itself - we should keep the spec document as short as possible
- test plan is even more client-specific than the spec
- the plan will grow (it's very much informal and now also incomplete w.r.t. some of the PR changes that have since been made to the spec)

**Comment by sickpig** [comment]
agreed

**Comment by ftrader** [comment]
Closed by https://github.com/BitcoinUnlimited/BUIP/pull/51
