### ISSUE TITLE
claimWhit me

### ISSUE THREAD

**Issue by petrr123** [BitcoinUnlimited/BUIP#59]

**Comment by JefferyThames** [comment]
Inter rate only my phone for me to use easy

**Comment by 6zmysl** [comment]
I  want to cancel my 2 transfer. I sent money 3 days ago and nobody received it. Proces is maximum 1 hour after this is too late. I have inf that I have to send money back to my account. This is adres first :  18Vcfa3UTy121ti2RGibQEeHkQLC3WCmoh  0.05391972 BCH  and second  1N7CMi66uTgriNasJadrcnsuwgUMNymamQ   0.00562311 BCH . I must to have it ASAP !!!!!!!!!!!!
